[build]
builder = "nixpacks"

[deploy]
startCommand = "python license_logger.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[mount]
source = "/data"
destination = "/data"