[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn license_logger:app"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "license-logger"