[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT license_logger:app"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[mounts]]
source = "/data"
destination = "/data"